kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "database.fullname" . }}
  labels: 
    {{- include "database.labels" . | nindent 4 }}
spec:
  storageClassName: managed-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage | default "5Gi" }}