apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4}}
spec:
  ports:
    - protocol: TCP
      port: {{ include "database.port" . }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4}}
