kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "database.fullname" . }}
  labels: 
    {{- include "database.labels" . | nindent 4 }}  

allowVolumeExpansion: true
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
